### ISSUE TITLE
Adding Instructions for training and testing the model

### ISSUE THREAD

**Issue by badri-reddy** [guyrosin/generating_timelines#1]

**Comment by guyrosin** [comment]
Hi,
Training the event-word classifier is pretty straightforward:
The dataset can be built by running the script in create_event_to_affected_words_script.py. Note that it requires a Wikipedia word2vec model (I used wikipedia2vec), and a directory containing temporal word2vec models (I used models built using the New York Times archive). Please see additional details in the paper.
Then, use create_classifier.py to train/test/evaluate the classifier.

Let me know if you have additional questions. Thanks!
